### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by EnderDev** [sentialx/electron-extensions#7]
I used the example code in the readme and it gave me this error
```js
App threw an error during load
TypeError: electron_1.protocol.registerSchemesAsPrivileged is not a function
    at Object.exports.registerProtocols (C:\Users\ender\Desktop\Dot Browser\desktop\node_modules\electron-extensions\build\main\services\protocols.js:8:25)
    at new ExtensionsMain (C:\Users\ender\Desktop\Dot Browser\desktop\node_modules\electron-extensions\build\main\index.js:20:20)
    at Object.<anonymous> (C:\Users\ender\Desktop\Dot Browser\desktop\node_modules\electron-extensions\build\main\index.js:71:26)
    at Object.<anonymous> (C:\Users\ender\Desktop\Dot Browser\desktop\node_modules\electron-extensions\build\main\index.js:73:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\ender\Desktop\Dot Browser\desktop\node_modules\electron-extensions\build\index.js:6:10)
    at Object.<anonymous> (C:\Users\ender\Desktop\Dot Browser\desktop\node_modules\electron-extensions\build\index.js:8:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at f (C:\Users\ender\Desktop\Dot Browser\desktop\build\main.js:2040:1092)
    at u (C:\Users\ender\Desktop\Dot Browser\desktop\build\main.js:2040:1430)`

**Comment by sentialx** [comment]
`electron-extensions` doesn't support outdated `electron` versions.
